import type { ParsedSpec, Template } from '@shared/types';

function makeTemplate(
  id: string,
  title: string,
  subtitle: string,
  description: string,
  domain: string,
  icon: string,
  tags: string[],
  completeness: number,
  questions: ParsedSpec['questions'],
  results: ParsedSpec['results'],
  progressSteps: ParsedSpec['progressSteps']
): Template {
  return {
    id,
    title,
    description,
    domain,
    icon,
    tags,
    completeness,
    spec: {
      title: { main: title, subtitle },
      metadata: { version: '1.0.0' },
      questions,
      results,
      progressSteps,
    },
  };
}

export const templateLibrary: Template[] = [
  makeTemplate(
    'network-path-selection',
    'Network Path Selection',
    'Choose the right Azure connectivity pattern',
    'Route engineers through latency, volume, and compliance decisions to select the right network path.',
    'Network',
    '🌐',
    ['network', 'azure', 'connectivity'],
    70,
    {
      q1: {
        title: 'What is the primary traffic source?',
        subtitle: 'Start with where the traffic originates.',
        infoBox: null,
        type: 'buttons',
        options: [
          { text: 'On-premises datacenter', next: 'q2', recommended: true, advanced: false },
          { text: 'Azure-to-Azure', next: 'q3', recommended: false, advanced: false },
          {
            text: "I don't know / Unsure",
            next: 'result-contact',
            recommended: false,
            advanced: false,
          },
        ],
      },
      q2: {
        title: 'How strict are the latency and reliability requirements?',
        subtitle: 'Use this to separate internet-based and dedicated paths.',
        infoBox: null,
        type: 'buttons',
        options: [
          {
            text: 'Dedicated predictable path required',
            next: 'result-expressroute',
            recommended: true,
            advanced: false,
          },
          {
            text: 'Standard encrypted tunnel is acceptable',
            next: 'result-vpn-gateway',
            recommended: false,
            advanced: false,
          },
          {
            text: "I don't know / Unsure",
            next: 'result-contact',
            recommended: false,
            advanced: false,
          },
        ],
      },
      q3: {
        title: 'What is the main design constraint?',
        subtitle: 'Pick the strongest requirement.',
        infoBox: null,
        type: 'buttons',
        options: [
          {
            text: 'Simple low-latency regional networking',
            next: 'result-vnet-peering',
            recommended: true,
            advanced: false,
          },
          {
            text: 'Global branch and hub connectivity',
            next: 'result-virtual-wan',
            recommended: false,
            advanced: false,
          },
          {
            text: 'Application entry and inspection',
            next: 'result-application-gateway',
            recommended: false,
            advanced: false,
          },
          {
            text: "I don't know / Unsure",
            next: 'result-contact',
            recommended: false,
            advanced: false,
          },
        ],
      },
    },
    {
      'result-vnet-peering': {
        title: 'Use VNet Peering',
        icon: '🔗',
        badge: { text: 'Standard', className: 'standard' },
        bestFor: ['Low-latency Azure-to-Azure connectivity between virtual networks'],
        keyBenefits: ['Simple setup with high throughput and low latency'],
        considerations: ['Plan address spaces carefully before peering'],
        whenNotToUse: ['When you need branch connectivity or dedicated private circuits'],
        techTags: ['network', 'peering'],
        docs: [
          {
            label: 'VNet peering overview',
            url: 'https://learn.microsoft.com/azure/virtual-network/virtual-network-peering-overview',
          },
        ],
        additionalConsiderations:
          'Use this as the default for direct Azure network interconnection unless a broader topology requires hub services.',
      },
      'result-vpn-gateway': {
        title: 'Use VPN Gateway',
        icon: '🛡️',
        badge: { text: 'Advanced', className: 'advanced' },
        bestFor: ['Encrypted site-to-site or point-to-site connectivity over the internet'],
        keyBenefits: ['Faster to provision than dedicated circuits'],
        considerations: ['Throughput and reliability depend on internet paths'],
        whenNotToUse: ['When strict deterministic performance is mandatory'],
        techTags: ['network', 'vpn'],
        docs: [
          {
            label: 'VPN Gateway overview',
            url: 'https://learn.microsoft.com/azure/vpn-gateway/vpn-gateway-about-vpngateways',
          },
        ],
        additionalConsiderations:
          'Use when private connectivity is preferred but budget or speed rules out dedicated connectivity.',
      },
      'result-expressroute': {
        title: 'Adopt ExpressRoute',
        icon: '🚄',
        badge: { text: 'Urgent', className: 'urgent' },
        bestFor: ['Mission-critical private connectivity from on-premises into Azure'],
        keyBenefits: ['Predictable performance and private routing'],
        considerations: ['Requires carrier coordination and longer lead times'],
        whenNotToUse: ['When the workload can tolerate internet-based encrypted connectivity'],
        techTags: ['network', 'expressroute'],
        docs: [
          {
            label: 'ExpressRoute overview',
            url: 'https://learn.microsoft.com/azure/expressroute/expressroute-introduction',
          },
        ],
        additionalConsiderations:
          'Use when compliance or business criticality justifies dedicated private connectivity.',
      },
      'result-virtual-wan': {
        title: 'Standardise on Azure Virtual WAN',
        icon: '🕸️',
        badge: { text: 'Advanced', className: 'advanced' },
        bestFor: ['Hub-and-spoke and branch connectivity at larger scale'],
        keyBenefits: ['Centralises routing and branch connectivity'],
        considerations: ['Design complexity is higher than direct peering'],
        whenNotToUse: ['When a small number of directly connected VNets is enough'],
        techTags: ['network', 'virtual-wan'],
        docs: [
          {
            label: 'Virtual WAN overview',
            url: 'https://learn.microsoft.com/azure/virtual-wan/virtual-wan-about',
          },
        ],
        additionalConsiderations:
          'Use when the network estate spans many branches, hubs, or geographies.',
      },
      'result-application-gateway': {
        title: 'Position Application Gateway',
        icon: '🚪',
        badge: { text: 'Standard', className: 'standard' },
        bestFor: ['Layer 7 ingress, routing, and inspection for web applications'],
        keyBenefits: ['Adds HTTP-aware routing and WAF capabilities'],
        considerations: ['It complements, rather than replaces, broader network transport choices'],
        whenNotToUse: ['When the need is only private network transport between networks'],
        techTags: ['network', 'application-gateway'],
        docs: [
          {
            label: 'Application Gateway overview',
            url: 'https://learn.microsoft.com/azure/application-gateway/overview',
          },
        ],
        additionalConsiderations: 'Use alongside the transport option, not as a substitute for it.',
      },
      'result-contact': {
        title: 'Review Requirements with the Network Team',
        icon: '📞',
        badge: { text: 'Support', className: 'support' },
        bestFor: ['Cases where the network intent is still unclear'],
        keyBenefits: ['Avoids locking in the wrong connectivity pattern'],
        considerations: ['Needs follow-up to capture latency, volume, and compliance requirements'],
        whenNotToUse: ['When the networking constraints are already documented and agreed'],
        techTags: ['support'],
        docs: [
          { label: 'Architecture review checklist', url: 'https://example.com/network-review' },
        ],
        additionalConsiderations:
          'Use this fallback to drive a short requirement-gathering conversation.',
      },
    },
    { q1: 20, q2: 45, q3: 70 }
  ),
  makeTemplate(
    'incident-severity-triage',
    'Incident Severity Triage',
    'Classify operational impact quickly',
    'Guide support engineers through urgency, impact, and workaround questions to assign severity.',
    'Operations',
    '🚨',
    ['operations', 'incident', 'triage'],
    65,
    {
      q1: {
        title: 'Is production currently affected?',
        subtitle: 'This is the first separator for urgency.',
        infoBox: null,
        type: 'buttons',
        options: [
          { text: 'Yes, production is affected', next: 'q2', recommended: true, advanced: false },
          {
            text: 'No, non-production or internal issue',
            next: 'q3',
            recommended: false,
            advanced: false,
          },
          {
            text: "I don't know / Unsure",
            next: 'result-contact',
            recommended: false,
            advanced: false,
          },
        ],
      },
      q2: {
        title: 'How broad is the user impact?',
        subtitle: 'Classify blast radius.',
        infoBox: null,
        type: 'buttons',
        options: [
          {
            text: 'Most or all users are blocked',
            next: 'result-p1-critical',
            recommended: true,
            advanced: false,
          },
          {
            text: 'A subset of users is affected',
            next: 'result-p2-high',
            recommended: false,
            advanced: false,
          },
          {
            text: "I don't know / Unsure",
            next: 'result-contact',
            recommended: false,
            advanced: false,
          },
        ],
      },
      q3: {
        title: 'Is there a viable workaround?',
        subtitle: 'Use workaround availability to separate urgency.',
        infoBox: null,
        type: 'buttons',
        options: [
          {
            text: 'No practical workaround',
            next: 'result-p3-medium',
            recommended: true,
            advanced: false,
          },
          {
            text: 'Yes, workaround exists',
            next: 'result-p4-low',
            recommended: false,
            advanced: false,
          },
          {
            text: "I don't know / Unsure",
            next: 'result-contact',
            recommended: false,
            advanced: false,
          },
        ],
      },
    },
    {
      'result-p1-critical': {
        title: 'Escalate as P1 Critical',
        icon: '🔥',
        badge: { text: 'Urgent', className: 'urgent' },
        bestFor: ['Major production incidents with broad user or revenue impact'],
        keyBenefits: ['Mobilises the fastest response path'],
        considerations: ['Needs incident commander and executive visibility'],
        whenNotToUse: ['When the impact is isolated or a workaround exists'],
        techTags: ['incident', 'p1'],
        docs: [{ label: 'Critical incident playbook', url: 'https://example.com/p1' }],
        additionalConsiderations:
          'Trigger the highest-severity bridge and response workflow immediately.',
      },
      'result-p2-high': {
        title: 'Treat as P2 High',
        icon: '⚠️',
        badge: { text: 'Advanced', className: 'advanced' },
        bestFor: ['Production incidents with material but partial user impact'],
        keyBenefits: ['Creates urgency without over-triggering the P1 process'],
        considerations: ['Watch for escalation if impact grows'],
        whenNotToUse: ['When only minor or internal impact exists'],
        techTags: ['incident', 'p2'],
        docs: [{ label: 'High severity guide', url: 'https://example.com/p2' }],
        additionalConsiderations:
          'Use when the incident is serious but not yet broadly catastrophic.',
      },
      'result-p3-medium': {
        title: 'Manage as P3 Medium',
        icon: '🧰',
        badge: { text: 'Standard', className: 'standard' },
        bestFor: ['Issues with meaningful friction but limited blast radius'],
        keyBenefits: ['Keeps the issue visible without pulling the full crisis workflow'],
        considerations: ['Track the workaround or mitigation path'],
        whenNotToUse: ['When customers are widely blocked'],
        techTags: ['incident', 'p3'],
        docs: [{ label: 'Medium severity guide', url: 'https://example.com/p3' }],
        additionalConsiderations: 'Use when response should be prompt but not crisis-driven.',
      },
      'result-p4-low': {
        title: 'Queue as P4 Low',
        icon: '📝',
        badge: { text: 'Support', className: 'support' },
        bestFor: ['Low-impact or routine issues with an acceptable workaround'],
        keyBenefits: ['Prevents over-escalation of minor requests'],
        considerations: ['Still capture enough detail for later action'],
        whenNotToUse: ['When the issue blocks production work'],
        techTags: ['incident', 'p4'],
        docs: [{ label: 'Low severity guide', url: 'https://example.com/p4' }],
        additionalConsiderations: 'Use when normal support handling is sufficient.',
      },
      'result-contact': {
        title: 'Clarify the Incident Scope',
        icon: '☎️',
        badge: { text: 'Support', className: 'support' },
        bestFor: ['Cases with missing impact data'],
        keyBenefits: ['Avoids the wrong severity assignment'],
        considerations: ['Ask for production scope, users affected, and workaround status'],
        whenNotToUse: ['When the incident facts are already confirmed'],
        techTags: ['support'],
        docs: [{ label: 'Incident intake checklist', url: 'https://example.com/intake' }],
        additionalConsiderations:
          'Use this fallback before assigning a severity under uncertainty.',
      },
    },
    { q1: 20, q2: 55, q3: 80 }
  ),
  makeTemplate(
    'cloud-compute-selection',
    'Cloud Compute Selection',
    'Choose the right Azure compute platform',
    'Help teams choose between Functions, App Service, AKS, and VMs based on control, scaling, and runtime needs.',
    'Cloud Architecture',
    '☁️',
    ['compute', 'azure', 'architecture'],
    80,
    {
      q1: {
        title: 'How much platform control do you need?',
        subtitle: 'Start by separating managed and self-managed options.',
        infoBox: null,
        type: 'buttons',
        options: [
          {
            text: 'Minimal infrastructure management',
            next: 'q2',
            recommended: true,
            advanced: false,
          },
          {
            text: 'Full OS and runtime control',
            next: 'result-virtual-machines',
            recommended: false,
            advanced: false,
          },
          {
            text: "I don't know / Unsure",
            next: 'result-contact',
            recommended: false,
            advanced: false,
          },
        ],
      },
      q2: {
        title: 'What execution pattern fits best?',
        subtitle: 'Use the main workload shape.',
        infoBox: null,
        type: 'buttons',
        options: [
          {
            text: 'Event-driven bursty functions',
            next: 'result-functions',
            recommended: true,
            advanced: false,
          },
          {
            text: 'Web app or API with predictable hosting',
            next: 'result-app-service',
            recommended: false,
            advanced: false,
          },
          {
            text: 'Containerised platform with orchestration',
            next: 'result-aks',
            recommended: false,
            advanced: false,
          },
          {
            text: "I don't know / Unsure",
            next: 'result-contact',
            recommended: false,
            advanced: false,
          },
        ],
      },
    },
    {
      'result-functions': {
        title: 'Adopt Azure Functions',
        icon: '⚡',
        badge: { text: 'Standard', className: 'standard' },
        bestFor: ['Event-driven and bursty workloads'],
        keyBenefits: ['Scales quickly with low operational overhead'],
        considerations: ['Cold-start and runtime constraints still matter'],
        whenNotToUse: ['When long-running stateful execution is the primary pattern'],
        techTags: ['functions', 'serverless'],
        docs: [
          {
            label: 'Functions overview',
            url: 'https://learn.microsoft.com/azure/azure-functions/functions-overview',
          },
        ],
        additionalConsiderations:
          'Use when the workload is naturally triggered by events or queues.',
      },
      'result-app-service': {
        title: 'Use Azure App Service',
        icon: '🧩',
        badge: { text: 'Standard', className: 'standard' },
        bestFor: ['Web apps and APIs on a managed PaaS'],
        keyBenefits: ['Simple hosting with managed scaling and deployment paths'],
        considerations: ['Less low-level control than VMs or Kubernetes'],
        whenNotToUse: ['When you need deep container orchestration or full OS access'],
        techTags: ['app-service', 'web'],
        docs: [
          {
            label: 'App Service overview',
            url: 'https://learn.microsoft.com/azure/app-service/overview',
          },
        ],
        additionalConsiderations:
          'Use when you want a managed web application platform with fast delivery.',
      },
      'result-aks': {
        title: 'Deploy to Azure Kubernetes Service',
        icon: '☸️',
        badge: { text: 'Advanced', className: 'advanced' },
        bestFor: ['Teams standardising on containers and orchestration'],
        keyBenefits: ['Supports complex containerised architectures'],
        considerations: ['Operational maturity requirements are higher'],
        whenNotToUse: ['When the workload does not need Kubernetes-level orchestration'],
        techTags: ['aks', 'kubernetes'],
        docs: [
          { label: 'AKS overview', url: 'https://learn.microsoft.com/azure/aks/intro-kubernetes' },
        ],
        additionalConsiderations:
          'Use when portability, orchestration, and platform consistency justify the complexity.',
      },
      'result-virtual-machines': {
        title: 'Provision Virtual Machines',
        icon: '🖥️',
        badge: { text: 'Advanced', className: 'advanced' },
        bestFor: ['Legacy or control-heavy workloads'],
        keyBenefits: ['Maximum control of the OS and runtime'],
        considerations: ['Operational burden is highest'],
        whenNotToUse: ['When a managed platform can satisfy the requirement'],
        techTags: ['vm', 'iaas'],
        docs: [
          {
            label: 'Virtual Machines overview',
            url: 'https://learn.microsoft.com/azure/virtual-machines/overview',
          },
        ],
        additionalConsiderations: 'Use when platform control is the primary decision driver.',
      },
      'result-contact': {
        title: 'Clarify the Compute Constraints',
        icon: '📋',
        badge: { text: 'Support', className: 'support' },
        bestFor: ['Cases where workload shape is not yet clear'],
        keyBenefits: ['Prevents locking into an unsuitable runtime'],
        considerations: ['Capture scaling, operations, and packaging constraints'],
        whenNotToUse: ['When the delivery and runtime model is already defined'],
        techTags: ['support'],
        docs: [
          { label: 'Compute decision checklist', url: 'https://example.com/compute-checklist' },
        ],
        additionalConsiderations:
          'Use this fallback to gather missing workload and team-operating-model details.',
      },
    },
    { q1: 25, q2: 60 }
  ),
  makeTemplate(
    'business-impact-assessment',
    'Business Impact Assessment',
    'Classify workload criticality and recovery expectations',
    'Classify services into impact tiers based on RTO, RPO, user count, and compliance needs.',
    'Risk & Compliance',
    '📊',
    ['risk', 'compliance', 'recovery'],
    75,
    {
      q1: {
        title: 'How quickly must service be restored?',
        subtitle: 'Use business recovery expectations first.',
        infoBox: null,
        type: 'buttons',
        options: [
          {
            text: 'Minutes to under 1 hour',
            next: 'result-tier-1',
            recommended: true,
            advanced: false,
          },
          { text: 'Same business day', next: 'result-tier-2', recommended: false, advanced: false },
          { text: 'One to two days', next: 'result-tier-3', recommended: false, advanced: false },
          {
            text: 'Longer than two days',
            next: 'result-tier-4',
            recommended: false,
            advanced: false,
          },
          {
            text: "I don't know / Unsure",
            next: 'result-contact',
            recommended: false,
            advanced: false,
          },
        ],
      },
    },
    {
      'result-tier-1': {
        title: 'Prioritise Tier 1 Mission Critical Controls',
        icon: '🏛️',
        badge: { text: 'Urgent', className: 'urgent' },
        bestFor: ['Revenue-critical or safety-critical services'],
        keyBenefits: ['Drives the strongest resilience requirements'],
        considerations: ['Cost and governance overhead are usually highest'],
        whenNotToUse: ['When the business can tolerate extended downtime'],
        techTags: ['tier-1', 'critical'],
        docs: [{ label: 'Criticality guidance', url: 'https://example.com/tier1' }],
        additionalConsiderations:
          'Use when downtime or data loss would create severe business impact.',
      },
      'result-tier-2': {
        title: 'Apply Tier 2 High Resilience Controls',
        icon: '🛡️',
        badge: { text: 'Advanced', className: 'advanced' },
        bestFor: ['Important business services with limited tolerance for interruption'],
        keyBenefits: ['Balances resilience with implementation effort'],
        considerations: ['Service-level expectations still need clear ownership'],
        whenNotToUse: [
          'When the workload is either clearly mission critical or clearly non-critical',
        ],
        techTags: ['tier-2'],
        docs: [{ label: 'High resilience guidance', url: 'https://example.com/tier2' }],
        additionalConsiderations:
          'Use for important services that are not the most critical revenue path.',
      },
      'result-tier-3': {
        title: 'Assign Tier 3 Standard Business Controls',
        icon: '📦',
        badge: { text: 'Standard', className: 'standard' },
        bestFor: ['Internal or non-urgent line-of-business services'],
        keyBenefits: ['Sets proportionate recovery and governance expectations'],
        considerations: ['Recovery can rely more on operational runbooks'],
        whenNotToUse: [
          'When the workload supports critical business deadlines or major customer journeys',
        ],
        techTags: ['tier-3'],
        docs: [{ label: 'Standard resilience guidance', url: 'https://example.com/tier3' }],
        additionalConsiderations: 'Use when business tolerance for downtime is moderate.',
      },
      'result-tier-4': {
        title: 'Treat as Tier 4 Standard',
        icon: '📁',
        badge: { text: 'Support', className: 'support' },
        bestFor: ['Low-impact or replaceable workloads'],
        keyBenefits: ['Avoids over-engineering the resilience design'],
        considerations: ['Basic backup and restore may be enough'],
        whenNotToUse: [
          'When the service materially affects customers, revenue, or compliance outcomes',
        ],
        techTags: ['tier-4'],
        docs: [{ label: 'Low criticality guidance', url: 'https://example.com/tier4' }],
        additionalConsiderations:
          'Use when the workload can tolerate slower recovery and lower investment.',
      },
      'result-contact': {
        title: 'Capture the Business Impact Details',
        icon: '🗂️',
        badge: { text: 'Support', className: 'support' },
        bestFor: ['Workloads without agreed recovery objectives'],
        keyBenefits: ['Forces the missing business conversation before design decisions'],
        considerations: ['Ask for RTO, RPO, compliance, and user impact'],
        whenNotToUse: ['When the business owner has already provided validated objectives'],
        techTags: ['support'],
        docs: [
          { label: 'Impact assessment checklist', url: 'https://example.com/impact-checklist' },
        ],
        additionalConsiderations: 'Use this fallback when key impact data is not yet defined.',
      },
    },
    { q1: 35 }
  ),
  makeTemplate(
    'new-team-member-onboarding',
    'New Team Member Onboarding',
    'Customise for your team and role',
    'A lightweight onboarding decision tree with explicit placeholders for team-specific content.',
    'HR & People',
    '👋',
    ['onboarding', 'people', 'hr'],
    50,
    {
      q1: {
        title: 'What is the new team member joining as?',
        subtitle: '[CUSTOMISE: your role paths here]',
        infoBox: '[CUSTOMISE: add role-specific expectations and team context.]',
        type: 'buttons',
        options: [
          { text: 'Engineering', next: 'result-engineering', recommended: true, advanced: false },
          { text: 'Operations', next: 'result-operations', recommended: false, advanced: false },
          {
            text: "I don't know / Unsure",
            next: 'result-contact',
            recommended: false,
            advanced: false,
          },
        ],
      },
    },
    {
      'result-engineering': {
        title: 'Prepare the Engineering Onboarding Path',
        icon: '🛠️',
        badge: { text: 'Support', className: 'support' },
        bestFor: ['Software and platform engineers joining the team'],
        keyBenefits: ['Provides a starting checklist you can tailor'],
        considerations: ['[CUSTOMISE: add your repositories, environments, and mentors.]'],
        whenNotToUse: ['When the hire is joining a non-engineering role'],
        techTags: ['onboarding', 'engineering'],
        docs: [{ label: 'Team handbook', url: 'https://example.com/team-handbook' }],
        additionalConsiderations: '[CUSTOMISE: your content here]',
      },
      'result-operations': {
        title: 'Prepare the Operations Onboarding Path',
        icon: '🧭',
        badge: { text: 'Support', className: 'support' },
        bestFor: ['Operations and support team members'],
        keyBenefits: ['Captures the first-run operations checklist'],
        considerations: ['[CUSTOMISE: add shift patterns, tooling, and escalation expectations.]'],
        whenNotToUse: ['When the role is not operations-focused'],
        techTags: ['onboarding', 'operations'],
        docs: [{ label: 'Operations runbook', url: 'https://example.com/operations-runbook' }],
        additionalConsiderations: '[CUSTOMISE: your content here]',
      },
      'result-contact': {
        title: 'Clarify the Onboarding Track',
        icon: '📚',
        badge: { text: 'Support', className: 'support' },
        bestFor: ['Cases where the role path is still unclear'],
        keyBenefits: ['Prevents assigning the wrong onboarding flow'],
        considerations: ['[CUSTOMISE: identify the hiring manager and buddy assignment process.]'],
        whenNotToUse: ['When the role and onboarding path are already fixed'],
        techTags: ['support'],
        docs: [{ label: 'Onboarding policy', url: 'https://example.com/onboarding-policy' }],
        additionalConsiderations: '[CUSTOMISE: your content here]',
      },
    },
    { q1: 30 }
  ),
];
